#!/usr/bin/env bash
# scipt that installs a NGINX server on a remote server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.html