#!/usr/bin/env bash
# scipt that installs a NGINX server on a remote server
sudo apt update
sudo apt -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
