#!/usr/bin/env bash
# scipt that installs a NGINX server and redirects from one page to another
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '42 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '43 a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start