#!/usr/bin/env bash
#install mysql version 5.7
sudo apt-key add signature.key
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update
sudo apt install-y -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
