#!/usr/bin/env bash
#the script prints no 1- 100 but FizzBuzz

num=1
while [ $num -le 100 ]
do
    if [ $((num%15)) = 0 ];
    then
        echo "FizzBuzz"
    elif [ $((num%3)) = 0 ];
    then
        echo "Fizz"
    elif [ $((num%5)) = 0 ];
    then
        echo "Buzz"
    else
        echo $num
    fi
    ((num++))
done
