#!/usr/bin/env bash
#the script prints "Best School"ten times using until loop

counter=1
while [ $counter -le 10 ]

do
    echo "Best School"
    if [ $counter -eq 9 ];
    then
        echo "Hi"
    fi
    ((counter++))
done
