#!/usr/bin/env bash
#loops 10 times while  and disrupt at 4th and 8th iteration

i=1;
while [ $i -le 10 ];
do
  if [ $i -eq 4 ]; then
  echo "bad luck"
  elif [ $i -eq 8 ]; then
  echo "good luck"
  else
  echo "Best School"
  fi
  ((i++));
done
