#!/usr/bin/env bash
#the script prints "Best School"ten times using while loop
#and case statements

counter=1
while [ $counter -le 20 ]
do

    case $counter in
        5)
        echo "bad luck from China"
        ;;
        10)
        echo "bad luck from Japan"
        ;;
        18)
        echo "bad luck from Italy"
        ;;
    esac
    echo $counter
    ((counter++))
done
