#!/usr/bin/env bash
#loops 20 times while  and disrupt at 4th and 9th, and 17th iteration

i=1;
while [ $i -le 20 ];
do
  case $i in
      "4" )
        ( echo $i
        echo "bad luck from China") ;;
      "9" )
        ( echo $i
        echo "bad luck from Japan") ;;
      "17" )
        ( echo $i
        echo "bad luck from Italy") ;;
      * )
        echo $i ;;
  esac
  ((i++))
done
