#!/usr/bin/env bash
#the script prints hours and minutes

hrs_counter=0

while [ $hrs_counter -le 12 ]
do
    echo "Hour: $hrs_counter"
        min_counter=1
        while [ $min_counter -lt 60 ]
        do
            echo $min_counter
            ((min_counter++))
        done
    ((hrs_counter++))
done
