#!/usr/bin/env bash
#this sript changes localhost to 127.0.0.2 and facebook to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
sed -i 's/.*127.0.0.1/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 a \ 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
